name: Portfolio CI

on:
  push:
    branches:
      - main

jobs:
  html-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check index.html exists
        run: |
          test -f index.html
          echo "index.html exists"